---
# Tasks for oh_my_zsh role
- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    version: master
  become: no

- name: Configure .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644
  become: no
  notify: restart_zsh
