---
# Tasks for common_cli_tools role
- name: Install Homebrew
  ansible.builtin.git:
    repo: https://github.com/Homebrew/brew.git
    dest: /opt/homebrew
    version: master
  become: true
  when: "'git' not in ansible_facts.packages"

- name: Ensure Homebrew is in PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="/opt/homebrew/bin:$PATH"'
    state: present
    create: yes
  become: false

- name: Install CLI tools
  loop: "{{ common_cli_tools }}"
  loop_control:
    loop_var: tool

- name: Install "{{ tool.name }}" with latest or undefined version
  ansible.builtin.homebrew:
    name: "{{ tool.name }}"
    state: present
    version: "{{ tool.version }}"
  become: false
  loop: "{{ common_cli_tools }}"
  loop_control:
    loop_var: tool
  when: tool.version == "latest" or tool.version is not defined
  notify: update_homebrew

- name: Install "{{ tool.name }}" with specific version
  ansible.builtin.homebrew:
    name: "{{ tool.name }}@{{ tool.version }}"
    state: present
  become: false
  loop: "{{ common_cli_tools }}"
  loop_control:
    loop_var: tool
  when: tool.version != "latest" and tool.version is defined
  notify: update_homebrew
