---
# Tasks for common_cli_tools role
- name: Install Homebrew
  ansible.builtin.git:
    repo: https://github.com/Homebrew/brew.git
    dest: /opt/homebrew
    version: master
  become: yes
  when: "'git' not in ansible_facts.packages"

- name: Ensure Homebrew is in PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="/opt/homebrew/bin:$PATH"'
    state: present
    create: yes
  become: no

- name: Install CLI tools
  loop: "{{ common_cli_tools }}"
  loop_control:
    loop_var: tool
  block:
    - name: Install "{{ tool.name }}"
      ansible.builtin.homebrew:
        name: "{{ tool.name }}"
        state: present
        version: "{{ tool.version }}"
      become: no
      notify: update_homebrew
  when: tool.version == "latest" or tool.version is not defined
  
    - name: Install "{{ tool.name }}" with specific version
      ansible.builtin.homebrew:
        name: "{{ tool.name }}@{{ tool.version }}"
        state: present
      become: no
      notify: update_homebrew
  when: tool.version != "latest" and tool.version is defined
